Fix image parser
crookedneighbor/markdown-it-linkify-images pull request #32
Opened 2019-05-19 16:37 UTC by HydeHunter2

Fixes a bug discussed by email.

### Changes
- The image parser becomes more secure.

----
UUID: af1477b6-509a-4611-b851-d7a8e3a9c02a

2019-05-19 16:45 UTC, HydeHunter2 commented
@crookedneighbor -- Hello again.
I tried to fix this bug by upgrading to the latest version of `markdown-it`, but It didn't help.

I'm sure that the bug appears here because if you remove the import of `markdown-it-linkify-images` from `habitica-markdown`, the bug disappears.

*This import:
https://github.com/HabitRPG/habitica-markdown/blob/2174d57581dfea9d8f44dde154f43bad6e787ff5/index.js#L17-L21

2019-05-19 18:29 UTC, crookedneighbor requested changes
Seems reasonable. Please add a test to verify this behavior.

2019-05-19 20:01 UTC, HydeHunter2 commented on index.js
> +      title = ' title="' + md.utils.escapeHtml(token.attrs[token.attrIndex('title')][1]) + '"'
While writing the test, I found another bug in `title` attribute.
So thanks for the tip to write the test 👍

2019-05-19 20:25 UTC, crookedneighbor approved these changes

2019-05-19 20:25 UTC, crookedneighbor commented
I’ll merge this and release it in a few days.

2019-05-20 02:16 UTC, merged

2019-05-20 02:20 UTC, crookedneighbor commented
Released wit v1.1.1